---

classname: "VCAP::Services::Marketplace::Appdirect::AppdirectMarketplace"

node_timeout: 15

# appdirect configuration
appdirect:
  endpoint: "https://example.com"
  key:    "k"
  secret: "s"

offering_whitelist: [ "fooservice" ]

offering_mapping:
  fooservice:
    name: foo
    provider: fooprovider
